import type { Metadata } from "next";
import Link from "next/link";
import styles from "../legal/legal.module.css";

export const metadata: Metadata = {
  title: "Terms of Use",
  description: "Terms governing use of the Jawly website and online services.",
  alternates: { canonical: "/term" },
};

const sections = [
  ["agreement", "Agreement"], ["audience", "Adult audience"], ["site", "Website use"],
  ["services", "Classroom services"], ["ip", "Intellectual property"], ["submissions", "Submissions"],
  ["third-parties", "Third parties"], ["disclaimers", "Disclaimers"], ["liability", "Liability"],
  ["indemnity", "Indemnity"], ["law", "Law and disputes"], ["changes", "Changes"], ["contact", "Contact"],
] as const;

export default function TermsPage() {
  return <main className={styles.page}>
    <header className={styles.hero}><div className={styles.heroInner}>
      <p className={styles.eyebrow}>TERMS OF USE</p>
      <h1>Terms for using the Jawly website.</h1>
      <p className={styles.intro}>These Terms govern access to jawly.kids and its online features. A separate written agreement may govern a demonstration, booking, classroom program, media session, or other Jawly service.</p>
      <p className={styles.effective}>Effective September 30, 2026</p>
    </div></header>
    <div className={styles.layout}>
      <nav className={styles.toc} aria-label="Terms of use sections"><strong>On this page</strong>{sections.map(([id,label])=><a key={id} href={`#${id}`}>{label}</a>)}</nav>
      <article className={styles.content}>
        <section id="agreement"><h2>1. Agreement to these Terms</h2><p>These Terms of Use form a binding agreement between you and Jawly concerning your access to and use of jawly.kids and related online features, which we call the “Site.” By accessing or using the Site, you agree to these Terms and our <Link href="/privacy">Privacy Statement</Link>. If you do not agree, do not use the Site.</p><p>If you use the Site for a school, center, company, or other organization, you represent that you are authorized to accept these Terms on its behalf. “You” then includes both you and that organization.</p></section>
        <section id="audience"><h2>2. Adult audience</h2><p>The Site is intended for adults, including educators, school and center operators, parents, caregivers, prospective performers, and business partners. It is not designed for children to use independently. You must be at least 18 years old and legally able to enter this agreement to submit an inquiry, join a waitlist, request a demonstration, or arrange services through the Site.</p><p>Do not submit a child’s personal information through the Site. If you believe a child has submitted information, contact us promptly.</p></section>
        <section id="site"><h2>3. Permitted use of the Site</h2><p>You may use the Site for lawful, personal, educational, or internal business purposes related to learning about Jawly and communicating with us. You agree not to:</p><ul><li>violate any law or another person’s rights;</li><li>misrepresent your identity, authority, affiliation, or intentions;</li><li>probe, disrupt, disable, overburden, or interfere with the Site or its security;</li><li>introduce malicious code or attempt unauthorized access;</li><li>scrape, harvest, or collect information from the Site through automated means without written permission;</li><li>copy, frame, mirror, or commercially exploit the Site or its content except as expressly allowed; or</li><li>use Jawly content, characters, recordings, or materials to train or develop an artificial intelligence or machine-learning system without our written permission.</li></ul><p>We may limit or suspend access when reasonably necessary to protect the Site, Jawly, our customers, children, or others.</p></section>
        <section id="services"><h2>4. Inquiries, availability, and classroom services</h2><p>Site content, service-area results, waitlists, demonstrations, and scheduling communications are invitations to discuss services. They are not a guarantee of availability, a reservation, or a binding offer unless Jawly confirms otherwise in writing.</p><p>Pricing, dates, program scope, cancellation terms, safety responsibilities, classroom supervision, media permissions, and other service details may be governed by a separate written agreement with the school, center, customer, or participant. If that agreement conflicts with these Terms concerning a classroom service, the separate agreement controls for that service.</p><p>Schools and centers remain responsible for their facilities, required staffing, supervision, emergency procedures, family communications, permissions, and compliance obligations. Jawly personnel will follow reasonable site rules communicated in advance, subject to safety and law.</p></section>
        <section id="ip"><h2>5. Intellectual property</h2><p>The Site and its content, including the Jawly name, logos, characters, stories, scripts, artwork, performances, audio, video, photographs, designs, software, inventions, program structures, and written materials, are owned by Jawly or used with permission. They are protected by copyright, trademark, patent, trade secret, and other laws.</p><p>Jawly grants you a limited, revocable, nonexclusive, nontransferable license to view and use the Site for its intended purposes. No other right or license is granted. You may not reproduce, adapt, distribute, publicly perform, display, sell, license, create derivative works from, or otherwise exploit Jawly materials without written permission, except where law expressly permits.</p><p>Jawly, its character names and designs, and associated marks are trademarks or trade dress of Jawly. You may not use them in a way that suggests sponsorship, endorsement, or affiliation without permission.</p></section>
        <section id="submissions"><h2>6. Communications, feedback, and submitted materials</h2><p>You retain ownership of material you submit to us. You grant Jawly a nonexclusive license to receive, reproduce, and use that material as reasonably necessary to respond, operate the Site, provide requested services, and meet legal obligations.</p><p>If you voluntarily provide an idea, suggestion, or feedback about Jawly without a written confidentiality agreement, you agree that we may use it without restriction or compensation. This does not apply to personal information, classroom media, or material governed by a separate written agreement or permission.</p><p>You represent that you have the right to submit any material you send and that it does not violate law, confidentiality, privacy, intellectual property, or another person’s rights.</p></section>
        <section id="third-parties"><h2>7. Third-party services and links</h2><p>The Site may link to or embed services operated by third parties, such as video, scheduling, email, payment, or social platforms. Jawly does not control those services and is not responsible for their content, availability, security, or practices. Your use of a third-party service is governed by that provider’s terms and privacy policy.</p></section>
        <section id="disclaimers"><h2>8. Disclaimers</h2><p>To the fullest extent permitted by law, the Site is provided “as is” and “as available.” Jawly disclaims all warranties, express or implied, including warranties of merchantability, fitness for a particular purpose, title, noninfringement, accuracy, and uninterrupted or error-free operation.</p><p>Website content is general information and is not medical, psychological, developmental, educational, legal, or other professional advice. Jawly is an enrichment experience. It does not diagnose, prevent, or treat any condition, and it is not a substitute for qualified care, individualized education, or required school services.</p><p>We aim to keep information accurate and current, but programs, availability, features, images, descriptions, and policies may change. Results and classroom experiences vary.</p></section>
        <section id="liability"><h2>9. Limitation of liability</h2><p>To the fullest extent permitted by law, Jawly and its owners, officers, employees, contractors, licensors, and service providers will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or for lost profits, revenue, data, goodwill, or opportunities, arising from or related to the Site.</p><p>To the fullest extent permitted by law, Jawly’s total liability for all claims arising from or related to the Site will not exceed the greater of $100 or the amount you paid Jawly specifically for use of the Site during the twelve months before the event giving rise to the claim. This limitation does not apply where prohibited by law or to liability that cannot lawfully be limited.</p></section>
        <section id="indemnity"><h2>10. Indemnity</h2><p>To the fullest extent permitted by law, you agree to defend, indemnify, and hold harmless Jawly and its owners, officers, employees, contractors, licensors, and service providers from claims, losses, liabilities, damages, judgments, costs, and reasonable legal fees arising from your unlawful use of the Site, your submitted material, your breach of these Terms, or your violation of another person’s rights. This obligation does not apply to the extent a claim results from Jawly’s own wrongful conduct.</p></section>
        <section id="law"><h2>11. Applicable law and disputes</h2><p>These Terms are governed by applicable United States federal law and the laws of the state where Jawly maintains its principal place of business, without regard to conflict-of-law principles. Any dispute relating to the Site that cannot be resolved informally will be brought in a court of competent jurisdiction in that state, and each party consents to that court’s jurisdiction and venue.</p><p>Before filing a claim, you and Jawly agree to make a good-faith effort to resolve the issue by written notice and at least 30 days of informal discussion. Nothing in this section prevents either party from seeking urgent relief to protect safety, privacy, confidential information, or intellectual property.</p><p>If any provision is unenforceable, it will be limited to the minimum extent necessary and the remaining provisions will continue. Our failure to enforce a provision is not a waiver. You may not assign these Terms without our written consent. Jawly may assign them in connection with a reorganization, financing, merger, acquisition, or transfer of the business.</p></section>
        <section id="changes"><h2>12. Changes and termination</h2><p>We may update these Terms by posting a revised version and changing the effective date. Changes apply prospectively. Your continued use of the Site after the new effective date means you accept the revised Terms. We may modify, suspend, or discontinue all or part of the Site at any time, subject to applicable law and any separate written agreement.</p></section>
        <section id="contact"><h2>13. Contact</h2><p>Questions about these Terms may be sent to:</p><p><strong>Jawly</strong><br/>Email: <a href="mailto:privacy@jawly.kids">privacy@jawly.kids</a><br/>Telephone: <a href="tel:+18887752959">1-888-77-JAWLY</a></p></section>
      </article>
    </div>
  </main>;
}
